# Generated by Django 3.0.5 on 2020-05-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200506_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.Rubric'),
        ),
    ]
