# Generated by Django 3.0.5 on 2020-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200405_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, max_length=375, verbose_name='Write something about your self'),
        ),
    ]
