# Generated by Django 3.0.5 on 2020-04-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_commentdeleteview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDeleteView',
        ),
    ]
